// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9Esb7HjzVelPsKFKLWt1-wy0409CB9GU',
    appId: '1:563308337115:web:845e2d38a67a3603d2b9fe',
    messagingSenderId: '563308337115',
    projectId: 'brainloom',
    authDomain: 'brainloom.firebaseapp.com',
    databaseURL: 'https://brainloom-default-rtdb.firebaseio.com',
    storageBucket: 'brainloom.appspot.com',
    measurementId: 'G-1M0KP0FMMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdcliYb9eoOBtcGRB9zO8fUcZ7p3PQ2Jw',
    appId: '1:821863625073:android:8b60ce8ce42768ab83c6d0',
    messagingSenderId: '821863625073',
    projectId: 'grad-project-ecommerce',
    storageBucket: 'grad-project-ecommerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLpa8vJsBXKVFiblK3rSGssd0alO_LRkU',
    appId: '1:821863625073:ios:891e8d417f6d42d683c6d0',
    messagingSenderId: '821863625073',
    projectId: 'grad-project-ecommerce',
    storageBucket: 'grad-project-ecommerce.appspot.com',
    iosBundleId: 'com.example.carAccessoriesEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLpa8vJsBXKVFiblK3rSGssd0alO_LRkU',
    appId: '1:821863625073:ios:76b9aa961aa3fe2983c6d0',
    messagingSenderId: '821863625073',
    projectId: 'grad-project-ecommerce',
    storageBucket: 'grad-project-ecommerce.appspot.com',
    iosBundleId: 'com.example.carAccessoriesEcommerce.RunnerTests',
  );
}